LOCAL_PATH := $(call my-dir)
HERE_PATH := $(LOCAL_PATH)

LOCAL_PATH := $(HERE_PATH)


include $(CLEAR_VARS)
LOCAL_MODULE := EGL_ANGLE
LOCAL_SRC_FILES := ANGLE/libEGL_angle.so
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := GLESv2_ANGLE
LOCAL_SRC_FILES := ANGLE/libGLESv2_angle.so
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := tinywrapper
LOCAL_SHARED_LIBRARIES := EGL_ANGLE GLESv2_ANGLE
LOCAL_SRC_FILES := main.c string_utils.c
LOCAL_C_INCLUDES := $(LOCAL_PATH)/tinywrapper
include $(BUILD_SHARED_LIBRARY)
