name: Android CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Build
      run: |
           $ANDROID_NDK_LATEST_HOME/ndk-build -j4 APP_PLATFORM=android-24 APP_BUILD_SCRIPT=./ltw/src/main/tinywrapper/Android.mk NDK_APPLICATION_MK=./ltw/src/main/tinywrapper/Application.mk NDK_PROJECT_PATH=.
           $ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip libs/*/libltw.so
    - name: Upload LTW
      uses: actions/upload-artifact@main
      with:
         name: output-aar
         path: libs/*/libltw.so
         if-no-files-found: error
       
