name: Android CI

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Build
      run: |
           $ANDROID_NDK_LATEST_HOME/ndk-build -j 4 APP_PLATFORM=android-24 APP_ABI=arm64-v8a APP_BUILD_SCRIPT=./tinywrapper/Android.mk NDK_APPLICATION_MK=./tinywrapper/Application.mk NDK_PROJECT_PATH=.
           find ./ -name '*.so' -execdir $ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip {} \;

    - name: Upload
      uses: actions/upload-artifact@main
      with:
         name: output
         path: libs/*.so
         retention-days: 7
       
